// GENERATED by scripts/make-samples.js — do not edit by hand.
// Captions follow the distribution playbook in
// apps/backend/src/operator/llm/playbook.ts.

export type SampleKind = 'photo' | 'composed' | 'graphic';

export interface Sample {
  file: string;
  kind: SampleKind;
  label: string;
  brand: string;
  alt: string;
  caption: string;
}

export const SAMPLES: readonly Sample[] = [
  {
    "file": "photo-cortados.jpg",
    "kind": "photo",
    "label": "Your photo, our words",
    "brand": "Rosa's Coffee",
    "alt": "Three cortados with latte art on a wooden table at a Pasadena coffee shop",
    "caption": "Three cortados, one table, zero laptops open. That's the goal.\n\nOur espresso is pulled on beans roasted twelve miles from here — which is why it tastes like something instead of just caffeine.\n\nSend this to the person you owe a coffee.\n\n#pasadenacoffee #oldtownpasadena #espressobar #coffeeshopsnearme"
  },
  {
    "file": "photo-window.jpg",
    "kind": "photo",
    "label": "Your photo, our words",
    "brand": "Rosa's Coffee",
    "alt": "Cozy window table with a french press inside a plant-filled Pasadena cafe",
    "caption": "The corner table by the window is open. It won't be in twenty minutes.\n\nRainy-day rules at our Pasadena coffee shop: french press, no rush, stay as long as your book lasts.\n\nSave this for the next grey afternoon.\n\n#pasadenacafe #rainydayreads #frenchpress #cozycoffeeshop"
  },
  {
    "file": "composed-promo.jpg",
    "kind": "composed",
    "label": "Photo + graphic",
    "brand": "Rosa's Coffee",
    "alt": "Milk being poured into a latte, with 50% off Friday offer text over the photo",
    "caption": "Half-price lattes this Friday. That's the whole post.\n\nEvery latte, all day, 7am–4pm at our Old Town Pasadena shop. Oat milk included, no minimum, no catch.\n\nSend this to whoever you're dragging along.\n\n#pasadenacoffee #lattedeals #oldtownpasadena #coffeespecials"
  },
  {
    "file": "composed-bouquet.jpg",
    "kind": "composed",
    "label": "Photo + graphic",
    "brand": "Fieldnote Florals",
    "alt": "Field of yellow poppies above a green panel announcing a spring bouquet launch",
    "caption": "Peonies are back, and they're only here for about three weeks.\n\nOur spring bouquet is cut and arranged the morning you order it, with local Pasadena delivery before noon.\n\nSave this so you don't miss the window.\n\n#pasadenaflorist #springbouquet #peonyseason #flowerdelivery"
  },
  {
    "file": "graphic-quote.jpg",
    "kind": "graphic",
    "label": "Pure graphic",
    "brand": "Rosa's Coffee",
    "alt": "Quote card reading the best ideas are brewed not forced, in cream on deep brown",
    "caption": "\"The best ideas are brewed, not forced.\"\n\nWritten on our chalkboard this morning by a regular who's been coming in since we opened. She's not wrong.\n\nSend this to someone who needs to slow down today.\n\n#pasadenacoffee #slowmornings #coffeeshopquotes #shoplocal"
  },
  {
    "file": "graphic-tips.jpg",
    "kind": "graphic",
    "label": "Pure graphic",
    "brand": "Fieldnote Florals",
    "alt": "Green tip card listing three ways to make a fresh flower bouquet last longer",
    "caption": "Your bouquet can last twice as long. Three things, none of them complicated.\n\n1. Re-cut the stems at an angle every other day\n2. Change the water — actually change it, don't top it up\n3. Keep them off the counter next to the fruit bowl. Ripening fruit gives off ethylene and wilts flowers fast\n\nSave this for your next bunch.\n\n#pasadenaflorist #flowercare #bouquettips #freshflowers"
  }
] as const;
